name: pomodoro
description: A Material Design 3 Pomodoro timer that runs on Android, iOS, Windows, macOS, Linux and the web.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
